#!/bin/bash

# OCF resource agent for a custom Master/Slave resource
# Place this script in /usr/lib/ocf/resource.d/custom/promotable

# Initialization:
# OCF_FUNCTIONS_DIR=${OCF_ROOT}/lib/heartbeat
# . ${OCF_FUNCTIONS_DIR}/ocf-shellfuncs

. /usr/lib/ocf/lib/heartbeat/ocf-shellfuncs

RESOURCE_NAME="promotable"
STATE_FILE="/statefiles/${RESOURCE_NAME}.state"

foobar_start() {
    # exit immediately if configuration is not valid
    foobar_validate_all || exit $?

    # if resource is already running, bail out early
    if foobar_monitor; then
        ocf_log info "Resource is already running"
        return $OCF_SUCCESS
    fi

    # actually start up the resource here (make sure to immediately
    # exit with an $OCF_ERR_ error code if anything goes seriously
    # wrong)
    
    echo Slave > $STATE_FILE
    # After the resource has been started, check whether it started up
    # correctly. If the resource starts asynchronously, the agent may
    # spin on the monitor function here -- if the resource does not
    # start up within the defined timeout, the cluster manager will
    # consider the start action failed

    # only return $OCF_SUCCESS if _everything_ succeeded as expected
    return $OCF_SUCCESS
}

foobar_stop() {
    local rc

    # exit immediately if configuration is not valid
    foobar_validate_all || exit $?

    foobar_monitor
    rc=$?
    case "$rc" in
        "$OCF_SUCCESS")
            # Currently running. Normal, expected behavior.
            ocf_log info "Resource is currently running"
            ;;
        "$OCF_RUNNING_MASTER")
            # Running as a Master. Need to demote before stopping.
            ocf_log info "Resource is currently running as Master"
            foobar_demote || \
                ocf_log warn "Demote failed, trying to stop anyway"
            ;;
        "$OCF_NOT_RUNNING")
            # Currently not running. Nothing to do.
            ocf_log info "Resource is already stopped"
            return $OCF_SUCCESS
            ;;
    esac

    # actually shut down the resource here (make sure to immediately
    # exit with an $OCF_ERR_ error code if anything goes seriously
    # wrong)
    echo Stopped > $STATE_FILE

    # After the resource has been stopped, check whether it shut down
    # correctly. If the resource stops asynchronously, the agent may
    # spin on the monitor function here -- if the resource does not
    # shut down within the defined timeout, the cluster manager will
    # consider the stop action failed

    # only return $OCF_SUCCESS if _everything_ succeeded as expected
    return $OCF_SUCCESS

}

foobar_monitor() {
    local rc

    foobar_validate_all || return $OCF_ERR_GENERIC

    if [ ! -f "$STATE_FILE" ]; then
        ocf_log err "Resource has failed"
        return $OCF_NOT_RUNNING
    fi

    if grep -q "Master" "$STATE_FILE"; then
        ocf_log info "Resource is running as Master on $(hostname)"
        return $OCF_RUNNING_MASTER
    elif grep -q "Slave" "$STATE_FILE"; then
        ocf_log info "Resource is running as Slave on $(hostname)"
        return $OCF_SUCCESS
    elif grep -q "Stopped" "$STATE_FILE"; then
        ocf_log info "Resource is not running on $(hostname)"
        return $OCF_NOT_RUNNING
    fi

    return $OCF_ERR_GENERIC  # Catch unexpected cases
}

foobar_validate_all() {
    return $OCF_SUCCESS
}

foobar_meta_data() {
    cat <<EOF
<?xml version="1.0"?>
<!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
<resource-agent name="${RESOURCE_NAME}" version="1.0">
    <version>1.0</version>
    <longdesc lang="en">
        This is a dummy OCF resource agent for a promotable resource.
    </longdesc>
    <shortdesc lang="en">Dummy OCF Master/Slave resource</shortdesc>
    <parameters/>
    <actions>
        <action name="start" />
        <action name="stop" />
        <action name="monitor" />
        <action name="promote" />
        <action name="demote" />
        <action name="notify" />
        <action name="meta-data" />
    </actions>
</resource-agent>
EOF
}

foobar_promote() {
    local rc

    # exit immediately if configuration is not valid
    foobar_validate_all || exit $?

    # test the resource's current state
    foobar_monitor
    rc=$?
    case "$rc" in
        "$OCF_SUCCESS")
            # Running as slave. Normal, expected behavior.
            ocf_log info "Resource is currently running as Slave on $(hostname)"
            ;;
        "$OCF_RUNNING_MASTER")
            # Already a master. Unexpected, but not a problem.
            ocf_log info "Resource is already running as Master on $(hostname)"
            return $OCF_SUCCESS
            ;;
        "$OCF_NOT_RUNNING")
            # Currently not running. Need to start before promoting.
            ocf_log info "Resource is currently not running on $(hostname)"
            foobar_start
            ;;
        *)
            # Failed resource. Let the cluster manager recover.
            ocf_log err "Unexpected error, cannot promote"
            exit $rc
            ;;
    esac

    # actually promote the resource here (make sure to immediately
    # exit with an $OCF_ERR_ error code if anything goes seriously
    # wrong)
    echo Master > $STATE_FILE || exit $OCF_ERR_GENERIC

    # After the resource has been promoted, check whether the
    # promotion worked. If the resource promotion is asynchronous, the
    # agent may spin on the monitor function here -- if the resource
    # does not assume the Master role within the defined timeout, the
    # cluster manager will consider the promote action failed.
    # while true; do
    #     foobar_monitor
    #     if [ $? -eq $OCF_RUNNING_MASTER ]; then
    #         ocf_log info "Resource promoted"
    #         break
    #     else
    #         ocf_log info "Resource still awaiting promotion"
    #         sleep 2
    #     fi
    # done

    # only return $OCF_SUCCESS if _everything_ succeeded as expected
    return $OCF_SUCCESS
}

foobar_demote() {
    foobar_validate_all || return $?

    foobar_monitor
    case $? in
        "$OCF_RUNNING_MASTER")
            ocf_log info "Demoting from Master..."
            ;;
        "$OCF_SUCCESS")
            ocf_log info "Already running as Slave"
            return $OCF_SUCCESS
            ;;
        "$OCF_NOT_RUNNING")
            ocf_log err "Resource is not running"
            return $OCF_ERR_GENERIC
            ;;
        *)
            ocf_log err "Unexpected state, cannot demote"
            return $OCF_ERR_GENERIC
            ;;
    esac

    echo "Slave" > "$STATE_FILE" || return $OCF_ERR_GENERIC
    ocf_log info "Resource successfully demoted"

    return $OCF_SUCCESS
}

foobar_migrate_to() {
    # exit immediately if configuration is not valid
    foobar_validate_all || exit $?

    # if resource is not running, bail out early
    if ! foobar_monitor; then
        ocf_log err "Resource is not running"
        exit $OCF_ERR_GENERIC
    fi

    # actually start up the resource here (make sure to immediately
    # exit with an $OCF_ERR_ error code if anything goes seriously
    # wrong)
    if [ "$(hostname)" == $OCF_RESKEY_CRM_meta_migrate_target ]; then
        echo Master > $STATE_FILE
    fi

    # only return $OCF_SUCCESS if _everything_ succeeded as expected
    return $OCF_SUCCESS
}

foobar_notify() {
    local type_op
    type_op="${OCF_RESKEY_CRM_meta_notify_type}-${OCF_RESKEY_CRM_meta_notify_operation}"

    ocf_log debug "Received $type_op notification."
    case "$type_op" in
	'pre-promote')
        if [ "$(hostname)" != $OCF_RESKEY_CRM_meta_notify_promote_uname ]; then
            echo Slave > $STATE_FILE
	    fi
        ;;
	'post-demote')
        if [ "$(hostname)" != $OCF_RESKEY_CRM_meta_notify_demote_uname ]; then
            echo Master > $STATE_FILE
	    fi
	    ;;
    esac

    return $OCF_SUCCESS
}

# Make sure meta-data and usage always succeed
case $__OCF_ACTION in
    meta-data)
        foobar_meta_data
        exit $OCF_SUCCESS
        ;;
esac

# Anything other than meta-data and usage must pass validation
foobar_validate_all || exit $?

# Translate each action into the appropriate function call
case $__OCF_ACTION in
    start)          foobar_start;;
    stop)           foobar_stop;;
    status|monitor)	foobar_monitor;;
    promote)        foobar_promote;;
    demote)         foobar_demote;;
    notify)         foobar_notify;;
    reload)         ocf_log info "Reloading..."
                    foobar_start
                    ;;
    validate-all)	
        return $OCF_SUCCESS
        ;;
    *)
        exit $OCF_ERR_UNIMPLEMENTED
        ;;
    esac
rc=$?

# The resource agent may optionally log a debug message
ocf_log debug "${OCF_RESOURCE_INSTANCE} $__OCF_ACTION returned $rc"
exit $rc

