AWSTemplateFormatVersion: "2010-09-09"
Description: "All-In-One resource provisioning to enroll to TCOP tools"

Parameters:
  # Global
  AccountIdentifier:
    Type: String
    Default: SsmParameter
    Description: "Choose 'SsmParameter' to use SSM or enter an account name directly"
  RetentionPolicy:
    Type: String
    AllowedValues: [Delete, Retain]
    Default: Delete
    Description: Retention policy for stack resources

  # Federation
  SAMLMetadataDocumentKeycloak:
    Type: String
    Description: "The full SAML Metadata XML document for Keycloak"
    Default: <md:EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" entityID="https://keycloak.thecanopener.local/realms/TCOP"><md:IDPSSODescriptor WantAuthnRequestsSigned="true" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol"><md:KeyDescriptor use="signing"><ds:KeyInfo><ds:KeyName>49v0vkO0H3Nv-hQr5MC8CJVAxQV7mWFzCk2YhBVMux0</ds:KeyName><ds:X509Data><ds:X509Certificate>MIIClzCCAX8CBgGajb/xZDANBgkqhkiG9w0BAQsFADAPMQ0wCwYDVQQDDARUQ09QMB4XDTI1MTExNjE3MzczN1oXDTM1MTExNjE3MzkxN1owDzENMAsGA1UEAwwEVENPUDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALPNI/yazq/1+tii94E2ajZGb/FLsULMuykyOVVVSOw4b6dgAmAXv1FmihFdswFfxScoQH5sjS718XRLV3uutpcOnZ8NUqVvJc+kBSd2M7uKRcODXb1BIe6mo5sutP5uceqlZXHePWP5tMEsoynJIj8L9UjYXjkrN5Fg2UeBz2sa1Etx+GcKKtzVIMmDCK33h7H7V1AIs9M+kG7h8+8YyHpXaVPAsYEsDptdDASaVI6pV+/rE1H1aFDA6gfxp/dapi0n11UScmvm7ZXRbqPsGyDOmTIom4z7l4B2ukiAG4NRmK7t+Pn1lv2SWjlC7gQqDXzjbjYf6DYpNasfyg90mlMCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEApOHPHAQ/ASUP657Xdh9mhFSbUpBIVMkbVnihhmo5jGxqBKh/h7lWHYA/Cw8Iba5pHndF8f/QaNCwFezRtArR/YUkwM4/PfZNS0H3MwWW5nrgVa6Cjn2HKO6ysEKgJ6/ynSZEV/ATjRKcPGjwA4TzvVEu6mS4F1bRW5oQKMKjymn2bh8ttv1ryVDwq3MgTI0m6R7Wi2N4iSaXWYIq0F/vHbPuwV/Kf5aCbVRjtIw9fbe68Nf9c8Zbef9/sRZqUeuqGYCG/UG5COzhMVq9etSBo9XxCqSvQNbbZMogi2f2RIWKR2Qgt84Zzk1hFLagEu/dNbc8U4WoGY1srojujbuJpQ==</ds:X509Certificate></ds:X509Data></ds:KeyInfo></md:KeyDescriptor><md:ArtifactResolutionService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://keycloak.thecanopener.local/realms/TCOP/protocol/saml/resolve" index="0"/><md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://keycloak.thecanopener.local/realms/TCOP/protocol/saml"/><md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://keycloak.thecanopener.local/realms/TCOP/protocol/saml"/><md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact" Location="https://keycloak.thecanopener.local/realms/TCOP/protocol/saml"/><md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://keycloak.thecanopener.local/realms/TCOP/protocol/saml"/><md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:persistent</md:NameIDFormat><md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:transient</md:NameIDFormat><md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified</md:NameIDFormat><md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</md:NameIDFormat><md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://keycloak.thecanopener.local/realms/TCOP/protocol/saml"/><md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://keycloak.thecanopener.local/realms/TCOP/protocol/saml"/><md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://keycloak.thecanopener.local/realms/TCOP/protocol/saml"/><md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact" Location="https://keycloak.thecanopener.local/realms/TCOP/protocol/saml"/></md:IDPSSODescriptor></md:EntityDescriptor>

# Backup Vaults and Plans
  BackupTagKey:
    Type: String
    Description: "Tag key to filter resources for backups. Tag values: prd or nprd"
    Default: backup_plan
  BackupProdRateHours:
    Type: Number
    Description: "Backup prd resources every X hours"
    MinValue: 1
    MaxValue: 24
    Default: 4
  BackupRetentionDays:
    Type: Number
    Description: "Retention for backups in days"
    MinValue: 1
    MaxValue: 365
    Default: 7
  BackupNonProdRateDays:
    Type: Number
    Description: "Backup prd resources every X days"
    MinValue: 1
    MaxValue: 7
    Default: 2 

#  ============ Resources ==================
Resources:
  ResolveAccountIdentifier:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 01-UTIL-ResolveOrgIdentifier.yaml
      Parameters:
        AccountIdentifier: !Ref AccountIdentifier

  BasicSvcRoles:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 02-IAM-BasicSvcRoles.yaml
      Parameters:
        OrgIdentifier: !GetAtt ResolveAccountIdentifier.Outputs.ResolvedOrgIdentifier
        RetentionPolicy: !Ref RetentionPolicy

  SamlFederation:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 02-IAM-SamlFederation.yaml
      Parameters:
        OrgIdentifier: !GetAtt ResolveAccountIdentifier.Outputs.ResolvedOrgIdentifier
        RetentionPolicy: !Ref RetentionPolicy
        SAMLMetadataDocumentKeycloak: !Ref SAMLMetadataDocumentKeycloak

  BackupVaultAndPlans:
    Type: AWS::CloudFormation::Stack
    DependsOn: BasicSvcRoles
    Properties:
      TemplateURL: 03-Backups-VaultsAndPlans.yaml
      Parameters:
        OrgIdentifier: !GetAtt ResolveAccountIdentifier.Outputs.ResolvedOrgIdentifier
        RetentionPolicy: !Ref RetentionPolicy
        TagKey: !Ref BackupTagKey
        ProdRateHours: !Ref BackupProdRateHours
        NonProdRateDays: !Ref BackupNonProdRateDays
        ProdRetentionDays: !Ref BackupRetentionDays
        NonProdRetentionDays: !Ref BackupRetentionDays