AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation stack for creating AWS backups, with backup vault and two plans based on tags.

Parameters:
  OrgIdentifier:
    Type: String
    Default: CUST-ENV
    Description: Identifier used for naming resources.

  TagKey:
    Type: String
    Description: Tag that will be used for resource filtering
    Default: backup_plan

  ProdTagValue:
    Type: String
    Description: Tag value that prod instances have
    Default: prd

  NonProdTagValue:
    Type: String
    Description: Tag value that non-prod instances have
    Default: nprd

  ProdRateHours:
    Type: Number
    Description: "Interval for Prod backups in hours"
    MinValue: 1
    MaxValue: 24
    Default: 4

  ProdRetentionDays:
    Type: Number
    Description: "Retention for Prod backups in days"
    MinValue: 1
    MaxValue: 365
    Default: 7

  NonProdRateDays:
    Type: Number
    Description: "Interval for Non-Prod backups in days"
    MinValue: 1
    MaxValue: 7
    Default: 2

  NonProdRetentionDays:
    Type: Number
    Description: "Retention for Non-Prod backups in days"
    MinValue: 1
    MaxValue: 365
    Default: 7

  KmsID:
    Type: String
    Description: >-
      KMS key ID (not ARN) for backup encryption. Use "default" to use AWS-managed alias/aws/backup.
    Default: "default"

  CopyToVaultARN:
    Type: String
    Description: >-
      ARN of the vault to copy backups to. Use "none" to disable copy.
    Default: "none"

  RetentionPolicy:
    Type: String
    AllowedValues: [Delete, Retain]
    Default: Delete
    Description: Retention policy for stack resources

Conditions:
  UseCustomKms: !Not [!Equals [!Ref KmsID, "default"]]
  EnableBackupCopy: !Not [!Equals [!Ref CopyToVaultARN, "none"]]

Resources:
  BackupVaultScheduled:
    Type: AWS::Backup::BackupVault
    DeletionPolicy: !Ref RetentionPolicy
    Properties:
      BackupVaultName: !Sub "${OrgIdentifier}-Scheduled-Vault"
      EncryptionKeyArn: !If
        - UseCustomKms
        - !Sub "arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${KmsID}"
        - !Ref "AWS::NoValue"

  BackupVaultAdHoc:
    Type: AWS::Backup::BackupVault
    DeletionPolicy: !Ref RetentionPolicy
    Properties:
      BackupVaultName: !Sub "${OrgIdentifier}-AdHoc-Vault"

  BackupExecutionCopyPolicy:
    Type: AWS::IAM::Policy
    DeletionPolicy: !Ref RetentionPolicy
    Condition: EnableBackupCopy
    Properties:
      PolicyName: !Sub "${OrgIdentifier}-SVC-AwsBackupEC2-PolicyForCopy"
      Roles:
        - !Sub "${OrgIdentifier}-SVC-AwsBackup"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowBackupCopy
            Effect: Allow
            Action:
              - backup:CopyFromBackupVault
              - backup:CopyIntoBackupVault
              - backup:DescribeBackupVault
              - backup:GetRecoveryPointRestoreMetadata
              - backup:StartCopyJob
              - backup:DescribeRecoveryPoint
              - backup:ListRecoveryPointsByBackupVault
            Resource: "*"
          - Sid: KmsPermissions
            Effect: Allow
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource:
              !If [
                UseCustomKms,
                !Sub "arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${KmsID}",
                "*",
              ]
          - Sid: KmsCreateGrantPermissions
            Effect: Allow
            Action: kms:CreateGrant
            Resource:
              !If [
                UseCustomKms,
                !Sub "arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${KmsID}",
                "*",
              ]
            Condition:
              ForAnyValue:StringEquals:
                kms:EncryptionContextKeys: aws:backup:backup-vault
              Bool:
                kms:GrantIsForAWSResource: true
              StringLike:
                kms:ViaService: backup.*.amazonaws.com

  ProdBackupSelection:
    Type: AWS::Backup::BackupSelection
    DeletionPolicy: !Ref RetentionPolicy
    Properties:
      BackupPlanId: !Ref ProdBackupPlan
      BackupSelection:
        SelectionName: !Sub "${OrgIdentifier}-Prod-Selection"
        IamRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/${OrgIdentifier}-SVC-AwsBackup"
        ListOfTags:
          - ConditionType: "STRINGEQUALS"
            ConditionKey: !Ref TagKey
            ConditionValue: !Ref ProdTagValue

  NonProdBackupSelection:
    Type: AWS::Backup::BackupSelection
    DeletionPolicy: !Ref RetentionPolicy
    Properties:
      BackupPlanId: !Ref NonProdBackupPlan
      BackupSelection:
        SelectionName: !Sub "${OrgIdentifier}-NonProd-Selection"
        IamRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/${OrgIdentifier}-SVC-AwsBackup"
        ListOfTags:
          - ConditionType: "STRINGEQUALS"
            ConditionKey: !Ref TagKey
            ConditionValue: !Ref NonProdTagValue

  ProdBackupPlan:
    Type: AWS::Backup::BackupPlan
    DeletionPolicy: !Ref RetentionPolicy
    Properties:
      BackupPlan:
        BackupPlanName: !Sub "${OrgIdentifier}-Prod-Plan"
        BackupPlanRule:
          - RuleName: !Sub "${OrgIdentifier}-Prod-Rule"
            TargetBackupVault: !Ref BackupVaultScheduled
            ScheduleExpression: !Sub "cron(0 */${ProdRateHours} * * ? *)"
            Lifecycle:
              DeleteAfterDays: !Ref ProdRetentionDays
            RecoveryPointTags:
              BackupPlan: !Sub "${OrgIdentifier}-Prod-Plan"
            StartWindowMinutes: 60
            CompletionWindowMinutes: 120
            CopyActions: !If
              - EnableBackupCopy
              - - DestinationBackupVaultArn: !Sub "${CopyToVaultARN}"
                  Lifecycle:
                    DeleteAfterDays: !Ref ProdRetentionDays
              - !Ref "AWS::NoValue"

  NonProdBackupPlan:
    Type: AWS::Backup::BackupPlan
    DeletionPolicy: !Ref RetentionPolicy
    Properties:
      BackupPlan:
        BackupPlanName: !Sub "${OrgIdentifier}-NonProd-Plan"
        BackupPlanRule:
          - RuleName: !Sub "${OrgIdentifier}-NonProd-Rule"
            TargetBackupVault: !Ref BackupVaultScheduled
            ScheduleExpression: !Sub "cron(0 0 */${NonProdRateDays} * ? *)"
            Lifecycle:
              DeleteAfterDays: !Ref NonProdRetentionDays
            RecoveryPointTags:
              BackupPlan: !Sub "${OrgIdentifier}-NonProd-Plan"
            StartWindowMinutes: 60
            CompletionWindowMinutes: 120

  EC2BackupSSMDocument:
    Type: AWS::SSM::Document
    DeletionPolicy: !Ref RetentionPolicy
    Properties:
      Name: !Sub "${OrgIdentifier}-EC2-AdHocBackups"
      DocumentType: Automation
      Content:
        schemaVersion: '0.3'
        description: "Trigger AWS Backup for an EC2 instance"
        parameters:
          InstanceId:
            type: "AWS::EC2::Instance::Id"
            description: "Select the EC2 instance to backup"
          RetentionDays:
            type: Integer
            description: "Number of days to retain the backup"
        mainSteps:
          - name: StartBackup
            action: "aws:executeAwsApi"
            inputs:
              Service: backup
              Api: StartBackupJob
              BackupVaultName: !Ref BackupVaultAdHoc
              IamRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/${OrgIdentifier}-SVC-AwsBackup"
              ResourceArn: !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/{{ InstanceId }}"
              Lifecycle:
                DeleteAfterDays: "{{ RetentionDays }}"

