AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates a SAML Identity Provider and basic roles across all AWS Org child accounts"

Parameters:
  OrgIdentifier:
    Type: String
    Description: Identifier to add as a prefix on roles and policies
  IdpName:
    Type: String
    Description: "The name of the SAML Identity Provider"
  SAMLMetadataDocument:
    Type: String
    Description: "The full SAML Metadata XML document"

Resources:
  SAMLIdentityProvider:
    Type: "AWS::IAM::SAMLProvider"
    Properties:
      Name: !Ref IdpName
      SamlMetadataDocument: !Ref SAMLMetadataDocument

  AdminRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: !Sub "${OrgIdentifier}-Administrator"
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Federated: !Sub "arn:aws:iam::${AWS::AccountId}:saml-provider/${IdpName}"
              Action: sts:AssumeRoleWithSAML
              Condition:
                StringEquals:
                  "SAML:aud": "https://signin.aws.amazon.com/saml"
        Policies:
          - PolicyName: !Sub "${OrgIdentifier}-Administrator-Policy"
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: "Deny"
                  Action:
                    - "iam:*"
                    - "sso:*"
                    - "identitystore:*"
                    - "organizations:*"
                    - "billing:*"
                    - "payment-method:*"
                    - "sts:AssumeRole"
                    - "sts:SetDefaultPolicyVersion"
                    - "cloudformation:CreateStackSet"
                    - "cloudformation:UpdateStackSet"
                    - "cloudformation:DeleteStackSet"
                    - "support:*"
                    - "kms:CreateKey"
                    - "kms:ScheduleKeyDeletion"
                  Resource: "*"

                - Effect: "Allow"
                  Action: 
                    - "aws-portal:View*"
                    - "account:Get*"
                    - "cloudtrail:*"
                    - "cloudwatch:*"
                    - "config:*"
                    - "ec2:*"
                    - "ecr:*"
                    - "ecr-public:*"                    
                    - "eks:*"
                    - "elasticfilesystem:*"
                    - "elasticloadbalancing:*"
                    - "kms:*"
                    - "lambda:*"
                    - "lambda:*"
                    - "logs:*"
                    - "route53:*"
                    - "route53domains:*"
                    - "route53resolver:*"
                    - "s3:*"
                    - "sqs:*"
                    - "ssm:*"
                  Resource: "*"

  ReadOnlyRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: !Sub "${OrgIdentifier}-ReadOnly"
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Federated: !Sub "arn:aws:iam::${AWS::AccountId}:saml-provider/${IdpName}"
              Action: sts:AssumeRoleWithSAML
              Condition:
                StringEquals:
                  "SAML:aud": "https://signin.aws.amazon.com/saml"

        Policies:
          - PolicyName: !Sub "${OrgIdentifier}-ReadOnly-Policy"
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: "Deny"
                  Action:
                    - "iam:*"
                    - "sso:*"
                    - "identitystore:*"
                    - "organizations:*"
                    - "billing:*"
                    - "payment-method:*"
                    - "sts:AssumeRole"
                    - "sts:SetDefaultPolicyVersion"
                    - "cloudformation:CreateStackSet"
                    - "cloudformation:UpdateStackSet"
                    - "cloudformation:DeleteStackSet"
                    - "support:*"
                    - "kms:CreateKey"
                    - "kms:ScheduleKeyDeletion"
                  Resource: "*"

                - Effect: "Allow"
                  Action:
                    - "aws-portal:View*"
                    - "account:Get*"
                    - "cloudtrail:LookupEvents"
                    - "cloudwatch:Describe*"
                    - "cloudwatch:Get*"
                    - "cloudwatch:List*"
                    - "config:Describe*"
                    - "config:Get*"
                    - "config:List*"
                    - "ec2:Describe*"
                    - "ec2:List*"
                    - "ec2:Get*"
                    - "ecr:Get*"
                    - "ecr:List*"
                    - "ecr:Describe*"
                    - "ecr-public:Get*"
                    - "ecr-public:List*"
                    - "ecr-public:Describe*"                    
                    - "eks:Describe*"
                    - "eks:List*"
                    - "elasticfilesystem:Describe*"
                    - "elasticloadbalancing:Describe*"
                    - "kms:Describe*"
                    - "kms:Get*"
                    - "lambda:Get*"
                    - "lambda:List*"
                    - "logs:Describe*"
                    - "logs:Get*"
                    - "logs:List*"
                    - "route53:Get*"
                    - "route53:List*"
                    - "route53domains:List*"
                    - "route53domains:Get*"
                    - "route53resolver:Get*"
                    - "route53resolver:List*"
                    - "s3:Get*"
                    - "s3:List*"
                    - "sns:Get*"
                    - "sns:List*"
                    - "sqs:Get*"
                    - "sqs:List*"
                    - "ssm:Describe*"
                    - "ssm:Get*"
                    - "ssm:List*"
                  Resource: "*"
Outputs:
  SAMLProviderArn:
    Description: "ARN of the created SAML Identity Provider"
    Value: !Ref SAMLIdentityProvider
  AdminRole:
    Description: "ARN of the Admin Role"
    Value: !Ref AdminRole
  ReadOnlyRole:
    Description: "ARN of the ReadOnly Role"
    Value: !Ref ReadOnlyRole