AWSTemplateFormatVersion: '2010-09-09'
Description: Provision personal CLI-only access user

Parameters:
  OrgIdentifier:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /org/account-name
    Description: Identifier used for naming resources. Defaults to SSM parameter

  Username:
    Type: String
    Description: Short form username for the user
Resources:

  CLIOnlyUserGeorge:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${OrgIdentifier}-USR-${Username}"
      LoginProfile: !Ref AWS::NoValue  # No console access
      Policies:
        - PolicyName: !Sub "${OrgIdentifier}-USR-${Username}-Policy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: "Deny"
                Action:
                - "sso:*"
                - "identitystore:*"
                - "organizations:*"
                - "billing:*"
                - "payment-method:*"
                - "sts:AssumeRole"
                - "sts:SetDefaultPolicyVersion"
                - "cloudformation:CreateStackSet"
                - "cloudformation:UpdateStackSet"
                - "cloudformation:DeleteStackSet"
                - "support:*"
                - "kms:CreateKey"
                - "kms:ScheduleKeyDeletion"
                Resource: "*"

              - Effect: "Allow"
                Action:
                - "aws-portal:View*"
                - "account:Get*"
                - "backup:*"
                - "cloudtrail:Describe*"
                - "cloudtrail:Get*"
                - "cloudtrail:List*"
                - "cloudwatch:*"
                - "config:*"
                - "iam:*"
                - "ec2:*"
                - "ecr:*"
                - "ecs:*"
                - "ecr-public:*"
                - "eks:*"
                - "elasticfilesystem:*"
                - "elasticloadbalancing:*"
                - "kms:*"
                - "lambda:*"
                - "logs:*"
                - "route53:*"
                - "route53domains:*"
                - "route53resolver:*"
                - "s3:*"
                - "sqs:*"
                - "ssm:*"
                Resource: "*"

