name: Sync to S3
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  REGION: "eu-central-1"             # Public ECR must use us-east-1
  S3_BUCKET: "tcop-prod-github-repos"    # Public ECR alias (e.g., "mycompany")
  S3_PREFIX: "ScriptAndNotes"       # ECR repository name

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: ${{ env.REGION }}

      - name: Sync Repo to S3
        run: |
          aws s3 sync . s3://${{ env.S3_BUCKET }}/${{ env.S3_PREFIX }} \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*"
